 
No internet connection... Press any key to resume ... 
COUNTRIES=AUT
SCENARIOS=high-vaccination scenario-comparison
 
 
############################################################################
RUNNING ANALYSIS (WEB)
############################################################################
 
 
[jupytext] Reading web-run-sim.ipynb in format ipynb
[jupytext] Loading 'web-run-sim.py'
[jupytext] Updating 'web-run-sim.ipynb'
[jupytext] Updating 'web-run-sim.py'
[jupytext] Reading web-meta.ipynb in format ipynb
[jupytext] Loading 'web-meta.py'
[jupytext] Updating 'web-meta.ipynb'
[jupytext] Updating 'web-meta.py'
[jupytext] Reading web-index.ipynb in format ipynb
[jupytext] Loading 'web-index.py'
[jupytext] Updating 'web-index.ipynb'
[jupytext] Updating 'web-index.py'
[jupytext] Reading web-country-scen.ipynb in format ipynb
[jupytext] Loading 'web-country-scen.py'
[jupytext] Updating 'web-country-scen.ipynb'
[jupytext] Updating 'web-country-scen.py'
[jupytext] Reading web-country-comp.ipynb in format ipynb
[jupytext] Loading 'web-country-comp.py'
[jupytext] Updating 'web-country-comp.ipynb'
[jupytext] Updating 'web-country-comp.py'
rm: cannot remove './LOGFILES/LOGFILE*.html': No such file or directory
 
RUNNING ANALYSIS FOR COUNTRY: AUT...
 
Input Notebook:  ./web-run-sim_.ipynb
Output Notebook: ./web-run-sim_.ipynb
Generating grammar tables from /home/jb/.local/lib/python3.7/site-packages/blib2to3/Grammar.txt
Writing grammar tables to /home/jb/.cache/black/20.8b1/Grammar3.7.3.final.0.pickle
Writing failed: [Errno 2] No such file or directory: '/home/jb/.cache/black/20.8b1/tmpefy146dv'
Generating grammar tables from /home/jb/.local/lib/python3.7/site-packages/blib2to3/PatternGrammar.txt
Writing grammar tables to /home/jb/.cache/black/20.8b1/PatternGrammar3.7.3.final.0.pickle
Writing failed: [Errno 2] No such file or directory: '/home/jb/.cache/black/20.8b1/tmp0rcf3869'
Executing:   0%|          | 0/17 [00:00<?, ?cell/s]Executing notebook with kernel: python3
Executing:   6%|▌         | 1/17 [00:01<00:17,  1.12s/cell]Executing:  24%|██▎       | 4/17 [00:01<00:10,  1.26cell/s]Executing:  35%|███▌      | 6/17 [00:02<00:09,  1.22cell/s]Executing:  59%|█████▉    | 10/17 [00:03<00:04,  1.71cell/s]Executing:  65%|██████▍   | 11/17 [00:20<00:03,  1.71cell/s]Executing:  71%|███████   | 12/17 [00:49<00:36,  7.35s/cell]Executing:  82%|████████▏ | 14/17 [00:49<00:15,  5.16s/cell]Executing:  88%|████████▊ | 15/17 [00:49<00:07,  3.65s/cell]Executing: 100%|██████████| 17/17 [00:50<00:00,  2.96s/cell]
[NbConvertApp] Converting notebook ./web-run-sim_.ipynb to html
[NbConvertApp] Writing 569610 bytes to web-run-sim_.html
 
SCENARIO: high-vaccination...
 
Input Notebook:  ./web-country-scen_.ipynb
Output Notebook: ./web-country-scen_.ipynb
Generating grammar tables from /home/jb/.local/lib/python3.7/site-packages/blib2to3/Grammar.txt
Writing grammar tables to /home/jb/.cache/black/20.8b1/Grammar3.7.3.final.0.pickle
Writing failed: [Errno 2] No such file or directory: '/home/jb/.cache/black/20.8b1/tmprcs0kbr6'
Generating grammar tables from /home/jb/.local/lib/python3.7/site-packages/blib2to3/PatternGrammar.txt
Writing grammar tables to /home/jb/.cache/black/20.8b1/PatternGrammar3.7.3.final.0.pickle
Writing failed: [Errno 2] No such file or directory: '/home/jb/.cache/black/20.8b1/tmphgk2qo86'
Executing:   0%|          | 0/41 [00:00<?, ?cell/s]Executing notebook with kernel: python3
Executing:   2%|▏         | 1/41 [00:00<00:37,  1.05cell/s]Executing:   7%|▋         | 3/41 [00:01<00:25,  1.46cell/s]Executing:  12%|█▏        | 5/41 [00:01<00:17,  2.02cell/s]Executing:  17%|█▋        | 7/41 [00:01<00:12,  2.62cell/s]Executing:  22%|██▏       | 9/41 [00:01<00:09,  3.52cell/s]Executing:  27%|██▋       | 11/41 [00:01<00:06,  4.55cell/s]Executing:  32%|███▏      | 13/41 [00:02<00:09,  2.94cell/s]Executing:  34%|███▍      | 14/41 [00:03<00:07,  3.72cell/s]Executing:  39%|███▉      | 16/41 [00:03<00:05,  4.81cell/s]Executing:  44%|████▍     | 18/41 [00:03<00:03,  6.08cell/s]Executing:  49%|████▉     | 20/41 [00:04<00:07,  2.88cell/s]Executing:  54%|█████▎    | 22/41 [00:04<00:05,  3.76cell/s]Executing:  59%|█████▊    | 24/41 [00:05<00:04,  3.59cell/s]Executing:  59%|█████▊    | 24/41 [00:06<00:04,  3.87cell/s]
Traceback (most recent call last):
  File "/home/jb/.local/bin/papermill", line 8, in <module>
    sys.exit(papermill())
  File "/home/jb/.local/lib/python3.7/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/jb/.local/lib/python3.7/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/jb/.local/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jb/.local/lib/python3.7/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/jb/.local/lib/python3.7/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/jb/.local/lib/python3.7/site-packages/papermill/cli.py", line 267, in papermill
    execution_timeout=execution_timeout,
  File "/home/jb/.local/lib/python3.7/site-packages/papermill/execute.py", line 122, in execute_notebook
    raise_for_execution_errors(nb, output_path)
  File "/home/jb/.local/lib/python3.7/site-packages/papermill/execute.py", line 234, in raise_for_execution_errors
    raise error
papermill.exceptions.PapermillExecutionError: 
---------------------------------------------------------------------------
Exception encountered at "In [20]":
  File "<ipython-input-20-128a0f9e989f>", line 1092
    add_plots = {
    ^
SyntaxError: keyword argument repeated


 
SCENARIO: scenario-comparison...
 
Input Notebook:  ./web-country-scen_.ipynb
Output Notebook: ./web-country-scen_.ipynb
Generating grammar tables from /home/jb/.local/lib/python3.7/site-packages/blib2to3/Grammar.txt
Writing grammar tables to /home/jb/.cache/black/20.8b1/Grammar3.7.3.final.0.pickle
Writing failed: [Errno 2] No such file or directory: '/home/jb/.cache/black/20.8b1/tmpar3aigaf'
Generating grammar tables from /home/jb/.local/lib/python3.7/site-packages/blib2to3/PatternGrammar.txt
Writing grammar tables to /home/jb/.cache/black/20.8b1/PatternGrammar3.7.3.final.0.pickle
Writing failed: [Errno 2] No such file or directory: '/home/jb/.cache/black/20.8b1/tmpzxcm90uz'
Executing:   0%|          | 0/41 [00:00<?, ?cell/s]Executing notebook with kernel: python3
Executing:   2%|▏         | 1/41 [00:01<00:41,  1.04s/cell]Executing:   7%|▋         | 3/41 [00:01<00:28,  1.32cell/s]Executing:  12%|█▏        | 5/41 [00:01<00:19,  1.81cell/s]Executing:  17%|█▋        | 7/41 [00:01<00:14,  2.33cell/s]Executing:  22%|██▏       | 9/41 [00:01<00:10,  3.10cell/s]Executing:  27%|██▋       | 11/41 [00:01<00:07,  4.08cell/s]Executing:  32%|███▏      | 13/41 [00:02<00:08,  3.16cell/s]Executing:  37%|███▋      | 15/41 [00:03<00:06,  4.11cell/s]Executing:  41%|████▏     | 17/41 [00:03<00:04,  5.28cell/s]Executing:  46%|████▋     | 19/41 [00:04<00:08,  2.61cell/s]Executing:  51%|█████     | 21/41 [00:04<00:05,  3.43cell/s]Executing:  56%|█████▌    | 23/41 [00:05<00:04,  4.47cell/s]Executing:  59%|█████▊    | 24/41 [00:06<00:04,  3.91cell/s]
Traceback (most recent call last):
  File "/home/jb/.local/bin/papermill", line 8, in <module>
    sys.exit(papermill())
  File "/home/jb/.local/lib/python3.7/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/jb/.local/lib/python3.7/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/jb/.local/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jb/.local/lib/python3.7/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/jb/.local/lib/python3.7/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/jb/.local/lib/python3.7/site-packages/papermill/cli.py", line 267, in papermill
    execution_timeout=execution_timeout,
  File "/home/jb/.local/lib/python3.7/site-packages/papermill/execute.py", line 122, in execute_notebook
    raise_for_execution_errors(nb, output_path)
  File "/home/jb/.local/lib/python3.7/site-packages/papermill/execute.py", line 234, in raise_for_execution_errors
    raise error
papermill.exceptions.PapermillExecutionError: 
---------------------------------------------------------------------------
Exception encountered at "In [20]":
  File "<ipython-input-20-128a0f9e989f>", line 1092
    add_plots = {
    ^
SyntaxError: keyword argument repeated


 
CREATING COUNTRY COMPARISONS...
 
Input Notebook:  ./web-country-comp_.ipynb
Output Notebook: ./web-country-comp_.ipynb
Generating grammar tables from /home/jb/.local/lib/python3.7/site-packages/blib2to3/Grammar.txt
Writing grammar tables to /home/jb/.cache/black/20.8b1/Grammar3.7.3.final.0.pickle
Writing failed: [Errno 2] No such file or directory: '/home/jb/.cache/black/20.8b1/tmp_ruf9vt5'
Generating grammar tables from /home/jb/.local/lib/python3.7/site-packages/blib2to3/PatternGrammar.txt
Writing grammar tables to /home/jb/.cache/black/20.8b1/PatternGrammar3.7.3.final.0.pickle
Writing failed: [Errno 2] No such file or directory: '/home/jb/.cache/black/20.8b1/tmpbkm9x4dh'
Executing:   0%|          | 0/41 [00:00<?, ?cell/s]Executing notebook with kernel: python3
Executing:   2%|▏         | 1/41 [00:01<00:40,  1.00s/cell]Executing:   7%|▋         | 3/41 [00:01<00:27,  1.39cell/s]Executing:  12%|█▏        | 5/41 [00:01<00:19,  1.87cell/s]Executing:  17%|█▋        | 7/41 [00:01<00:13,  2.57cell/s]Executing:  24%|██▍       | 10/41 [00:01<00:08,  3.48cell/s]Executing:  29%|██▉       | 12/41 [00:02<00:11,  2.51cell/s]Executing:  34%|███▍      | 14/41 [00:03<00:09,  2.98cell/s]Executing:  37%|███▋      | 15/41 [00:03<00:07,  3.43cell/s]Executing:  39%|███▉      | 16/41 [00:03<00:06,  3.85cell/s]Executing:  41%|████▏     | 17/41 [00:03<00:05,  4.23cell/s]Executing:  44%|████▍     | 18/41 [00:04<00:05,  4.48cell/s]Executing:  46%|████▋     | 19/41 [00:04<00:04,  4.69cell/s]Executing:  49%|████▉     | 20/41 [00:04<00:04,  4.85cell/s]Executing:  51%|█████     | 21/41 [00:05<00:10,  1.86cell/s]Executing:  54%|█████▎    | 22/41 [00:05<00:08,  2.20cell/s]Executing:  56%|█████▌    | 23/41 [00:06<00:06,  2.63cell/s]Executing:  59%|█████▊    | 24/41 [00:06<00:05,  3.12cell/s]Executing:  61%|██████    | 25/41 [00:08<00:14,  1.08cell/s]Executing:  63%|██████▎   | 26/41 [00:09<00:12,  1.19cell/s]Executing:  66%|██████▌   | 27/41 [00:10<00:11,  1.27cell/s]Executing:  68%|██████▊   | 28/41 [00:10<00:10,  1.25cell/s]Executing:  71%|███████   | 29/41 [00:11<00:08,  1.38cell/s]Executing:  73%|███████▎  | 30/41 [00:11<00:07,  1.47cell/s]Executing:  76%|███████▌  | 31/41 [00:12<00:06,  1.47cell/s]Executing:  78%|███████▊  | 32/41 [00:13<00:05,  1.54cell/s]Executing:  80%|████████  | 33/41 [00:13<00:05,  1.57cell/s]Executing:  83%|████████▎ | 34/41 [00:14<00:04,  1.66cell/s]Executing:  85%|████████▌ | 35/41 [00:14<00:03,  1.74cell/s]Executing:  88%|████████▊ | 36/41 [00:15<00:02,  1.75cell/s]Executing:  90%|█████████ | 37/41 [00:15<00:02,  1.76cell/s]Executing:  93%|█████████▎| 38/41 [00:16<00:01,  1.80cell/s]Executing:  95%|█████████▌| 39/41 [00:17<00:01,  1.82cell/s]Executing:  98%|█████████▊| 40/41 [00:17<00:00,  1.81cell/s]Executing: 100%|██████████| 41/41 [00:18<00:00,  1.62cell/s]Executing: 100%|██████████| 41/41 [00:18<00:00,  2.17cell/s]
 
CREATING INDEX...
 
Input Notebook:  ./web-index_.ipynb
Output Notebook: ./web-index_.ipynb
Generating grammar tables from /home/jb/.local/lib/python3.7/site-packages/blib2to3/Grammar.txt
Writing grammar tables to /home/jb/.cache/black/20.8b1/Grammar3.7.3.final.0.pickle
Writing failed: [Errno 2] No such file or directory: '/home/jb/.cache/black/20.8b1/tmpnzb58xdx'
Generating grammar tables from /home/jb/.local/lib/python3.7/site-packages/blib2to3/PatternGrammar.txt
Writing grammar tables to /home/jb/.cache/black/20.8b1/PatternGrammar3.7.3.final.0.pickle
Writing failed: [Errno 2] No such file or directory: '/home/jb/.cache/black/20.8b1/tmpkslkms81'
Executing:   0%|          | 0/20 [00:00<?, ?cell/s]Executing notebook with kernel: python3
Executing:   5%|▌         | 1/20 [00:01<00:20,  1.06s/cell]Executing:  25%|██▌       | 5/20 [00:01<00:11,  1.33cell/s]Executing:  35%|███▌      | 7/20 [00:01<00:07,  1.83cell/s]Executing:  45%|████▌     | 9/20 [00:01<00:04,  2.52cell/s]Executing:  60%|██████    | 12/20 [00:01<00:02,  3.43cell/s]Executing:  75%|███████▌  | 15/20 [00:01<00:01,  4.64cell/s]Executing:  90%|█████████ | 18/20 [00:01<00:00,  6.21cell/s]Executing: 100%|██████████| 20/20 [00:02<00:00,  9.45cell/s]
[NbConvertApp] Converting notebook web-index_.ipynb to notebook
[NbConvertApp] Writing 24867 bytes to web-index_.ipynb
[NbConvertApp] Converting notebook web-country-scen_.ipynb to notebook
[NbConvertApp] Writing 151816 bytes to web-country-scen_.ipynb
 
 
############################################################################
END OF ANALYSIS (WEB)
############################################################################
 
 
 
RUNTIME: 107 s (0 h)
 
